### ISSUE TITLE
Write ADR(s) about Operator Architecture

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/documentation#34]
1) The spark operator uses a state machine approach and saves commands in the status while the ZK and Kafka operators always try to figure out the next action from the current spec and the actual current state.

We need to make a decision on which style we want to use and document why.

2) We should make a decision on whether to use Java or Rust for Operators (or both) but it should be a concious one.

3) ZK & Kafka currently don't use matchLabels etc. to assign nodes to objects, they assign it manually. The Spark operator however does. We should decide on one way (or document why it makes sense to differ)

**Comment by lfrancke** [comment]
## 1. General architecture

For reference: https://github.com/kubernetes/kubernetes/issues/72637
Postponed for now.

## 2. Java or Rust

Pro Rust:
* Easier to write resilient code
* Easy to deploy (single binary)

Con Rust:
* Hard to find contributors/employees, not easy to learn
* Mocking (for tests) is hard/impossible to do

Pro Java:
* Most of the tools we support are Java based so we can reuse clients, config definitions etc.
    * Malte says he hasn't benefited from it being Java based at all
* Easier to find contributors/employees
* Large ecosystem of tools, frameworks etc.

Con Java:
* Clients need a JVM installed on their servers running the operators

Pro Both:
* More flexibility (can hire contributors for both languages, use the tools that fit etc.)

Con Both:
* Can write a single library with helper functions 

*Note*: Java has (at least) two Kubernetes clients: Fabric8 and the official K8S Java bindings. We need to decide between the two.


## 3. Node Assignments

For now we'll use a structure that looks like this:

```
  worker:
    selectors:
      - name: "worker-1-core-4g-memory-bawa-virtualbox"
        instancesPerNode: 1
        cores: "1" // example
        memory: "4g" // example
        nodeName: "foobar"
```

So we'll have one or more selectors per role type and each selector has a `nodeName` property which is used to assign this role to a specific node. This means we'll not use the K8S scheduler for now.

`instancesPerNode` does not have to be supported
Each selector can have additional properties (`name`, `cores` and `memory` in this example).

This paves the way for a full support of `matchLabels` later:

```
      - name: "worker-2-core-5g-memory-bawa-virtualbox"
        instances: 1
        cores: "2"
        memory: "5g"
        matchLabels:
          kubernetes.io/hostname: "bawa-virtualbox"
```
