### ISSUE TITLE
Getting Started uses more complicated kind invocation than need be

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/documentation#428]
The docs currently say

```
kind create cluster --name quickstart --config - << EOF
---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: node=quickstart-1
```

but all of that "extra" stuff is not really needed.
It is however used further down the page:

```kubectl get nodes --selector=node=quickstart-1 -o wide```

This ticket should ideally get rid of the "extra" bit and find another way for the kubectl command to work.
If that is not possible I'd like to have a section above this that says that you only need the extra bits for the purpose of this tutorial but for a real one use "this" command instead.
